### ISSUE TITLE
git / github introduction tutorial

### ISSUE THREAD

**Issue by harshula** [ACCESS-NRI/access-hive.org.au#242]
Once we have a list of recommended git / github introduction tutorials, perhaps we can pick one video and one textual tutorial and put the links on the training_and_policies section?

**Comment by dougiesquire** [comment]
The [Hello World github tutorial](https://docs.github.com/en/get-started/quickstart/hello-world) looks like a nice intro to the Github UI

**Comment by tammasloughran** [comment]
Whenever I forget something for git, I like to use this [website](https://rogerdudler.github.io/git-guide/) as a quick-reference guide/cheat sheet. Please excuse the obscenity on it but it's very on point.

**Comment by ccarouge** [comment]
For info, there is already a link to some Git and GitHub training information on the [ACCESS-Hive](https://access-hive.org.au/training_and_policies/additional_training/). It points to a tutorial in ACCESS-NRI organisation based upon resources from the web. 

Happy for better resources to be listed there though.

**Comment by harshula** [comment]
@ccarouge We definitely need to find and recommend a much better video tutorial than the one currently listed.

**Comment by rogeredberg** [comment]
Software Carpentry has a good introductory course at [https://swcarpentry.github.io/git-novice/](https://swcarpentry.github.io/git-novice/.) 

I'm working on Carpentries instructor certification and hope to leverage this and other courses for ACCESS community purposes in 2023.

**Comment by rbeucher** [comment]
I second @dougiesquire and use the GitHub tutorial. That seems natural to me...

**Comment by harshula** [comment]
@heidinett said this video tutorial was good: [Git and GitHub Tutorial For Beginners | Full Course [2021]](https://www.youtube.com/watch?v=3fUbBnN_H2c)

**Comment by heidinett** [comment]
> Software Carpentry has a good introductory course at [https://swcarpentry.github.io/git-novice/](https://swcarpentry.github.io/git-novice/.)

I found this a good introductory-level resource for learning the basics of GitHub. Might be a useful resource for others to get started with using Git.

**Comment by heidinett** [comment]
> The [Hello World github tutorial](https://docs.github.com/en/get-started/quickstart/hello-world) looks like a nice intro to the Github UI

I found this a good resource for someone who already understands the basic concepts / workflow of GitHub. Someone completely new to it might find this mostly text-based resource a little overwhelming as it seems a basic knowledge of the fundamentals of GitHub is required to find what you are looking for.

**Comment by atteggiani** [comment]
https://github.com/MonashMath/SCI1022/blob/master/Git.md#16-the-concept-of-staging-area-creating-our-first-commit

**Comment by atteggiani** [comment]
@KAUR1984 Please check whether you think any of this resources can be added to [Additional GitHub learning resources](https://access-hive.org.au/development-website/about/contribute/contribute_on_github/#additional-github-learning-resources).
The last link I posted is a very extensive course on _git_, if anyone is interested, so maybe we could add that.
I would then close this issue.

**Comment by KAUR1984** [comment]
Sounds good to me, we are good to include - one intro and one extensive tutorial on GitHub under this section for now.
