### ISSUE TITLE
Cross-checking content between ACCESS-NRI, old ACCESS-Hive and new ACCESS-Hive websites

### ISSUE THREAD

**Issue by atteggiani** [ACCESS-NRI/access-hive.org.au#291]
## Description
Check content is consistent (and possibly not duplicate) between the two websites.

## Why
To achieve consistency between the UIs of the two websites and to enhance the experience of the end-users.

## Close Criteria
- [ ] Make the UIs consistent for ACCESS-NRI and ACCESS-HIVE websites. 
- [ ] Avoid any duplicate data or explanations in the two websites. 
- [ ] Old hive content to be mapped/migrated across to the new hive page. 
- [ ] Ensuring clear navigation of the ACCESS-NRI home page

**Comment by svenbuder** [comment]
Hi @NBateman-bit, adding you to this issue to make sure we (@KAUR1984, @atteggiani, @svenbuder, and you) are all involved in this process.

**Comment by atteggiani** [comment]
Not relevant anymore
