### ISSUE TITLE
Find ways for letting the users know that they have run the model correctly

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-NRI/access-hive.org.au#295]
## Description
Brainstorm ways of letting the users know that they have run the model correctly at the end and could they tweak it according to their own research needs. 

## Why
For enhanced user experience for the hive website.

## Close Criteria
- [ ] Write some examples to achieve the above mentioned goal. 
- [ ] Implement those examples on the Hive page.

**Comment by svenbuder** [comment]
Who do we have to tell about the outcome of this issue?
ESM: Davide
CM:   Davide
AM:   TBD
OM:  Jasmeen

**Comment by KAUR1984** [comment]
As per the discussion in the hive docs meeting, we could have a table outlining the `Expected/learning outcomes` specifying the expectations that at the end of this running process you should be getting this...

> @kdruken sharepoint notes

**Comment by atteggiani** [comment]
This is a relatively old issue, and I think as much as we can always improve the clarity on the "How to run ..." pages, the usual way to check that the model ran correctly is by checking the outputs (and there is information on how to do it).

I would close this issue.
@ACCESS-NRI/webops
