### ISSUE TITLE
Double check proper acknowledgement of all information sources across the hive 

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-NRI/access-hive.org.au#312]
## Description
Since, Hive is a portal for gathering all the related documentation, it is essential to properly acknowledge all these sources.

## Why
For respecting the referencing purposes of the sources.

## Close Criteria
- [ ] Double check all the references on the hive page.

**Comment by atteggiani** [comment]
I think this issue is similar or linked to #660.

I would close this issue.
@ACCESS-NRI/webops

**Comment by KAUR1984** [comment]
I think this is for making sure we have referenced everything on the Hive. This was created almost a year ago, happy to close this one as we double checked the referencing on the workshop...
