### ISSUE TITLE
Discuss where on the ACCESS-HIVE website do glossaries go?

### ISSUE THREAD

**Issue by svenbuder** [ACCESS-NRI/access-hive.org.au#313]
## Description
We will have several glossaries for ACCESS-NRI jargon, CMIP6, etc. They are currently under `community_resources/glossaries`

Is that the right place?

## Why
We want the users to easily find the relevant glossary and understand our jargon.

## Close Criteria

- [ ] Consensus on where in the navigation to put the file

**Comment by KAUR1984** [comment]
_Sprint meeting suggestions:_ 

- Could add a tooltip to the acronyms. For that to be visible, could make subtle UI adjustments. 
- Include the glossary may be the home page?

**Comment by KAUR1984** [comment]
Hi @svenbuder ! Realised this as an old one, Is this issue still relevant ?

**Comment by atteggiani** [comment]
Not relevant anymore.
