### ISSUE TITLE
Update the README of the `access-hive` github repository 

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-NRI/access-hive.org.au#316]
## Description
Modify the README to include all the relevant information related to ACCESS-Hive repo. Also including important links for `how to contribute` guides.

## Why
To have a comprehensive README of the ACCESS-Hive repository. 

## Close Criteria
- [ ] Add the relevant documentation to the readme of the access-hive repo.

**Comment by KAUR1984** [comment]
Partial implementation of this issue addressed in PR - https://github.com/ACCESS-Hive/access-hive.github.io/pull/327. 

**Tasks completed:** 
- [ ] Added draft `how to contribute` guide on ACCESS-Hive readme

**Comment by KAUR1984** [comment]
Thanks heaps for flagging this issue @svenbuder !

**Comment by atteggiani** [comment]
Fixed with recent PRs.
