### ISSUE TITLE
Decision needed: Is a welcome message needed on Hive landing page?

### ISSUE THREAD

**Issue by heidinett** [ACCESS-NRI/access-hive.org.au#345]
Is a welcome message needed on Hive landing page? That is, one that sets the users expectations of which audience the current Hive documentation is aimed at (beginner level)? 
Perhaps also good to mention that this is the first iteration of the documentation and that new tools and configurations are expected in the future for more experienced users, so stay tuned, etc.

**Comment by KAUR1984** [comment]
Suggestions from the sprint meeting: 

- Removing the white (empty) space above and below the welcome message.
