### ISSUE TITLE
Placeholder for additional information on Hive page

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-NRI/access-hive.org.au#366]
## Description
Brainstorm ways of including additional informations and guides on the hive page. Do we need a separate tab or section for additional information or any other better approach?

## Why
Enhanced UI experience of the hive page covering all possible use cases for the hive. 

## Close Criteria
- [ ] Brainstorm different options for including additional information on the hive page. 
- [ ] Implement the decided option on the Hive.

**Comment by KAUR1984** [comment]
In the bigger docs meeting, suggestions were made for renaming the `Community Resources` section to `Resources`, to two sub-sections :

- General resources.
- Community resources.

**Comment by atteggiani** [comment]
I think the new "External Resources" solves this.
@KAUR1984 

I would close it.

**Comment by KAUR1984** [comment]
I am good with closing this issue. `External Resources` section could be used as a workaround for this one.
