### ISSUE TITLE
Fix paragraph titles getting covered by top navigation bar when clicked on toc

### ISSUE THREAD

**Issue by atteggiani** [ACCESS-NRI/access-hive.org.au#392]
## Description
When clicking on a table of content link, the title is getting covered by the top navigation bar. 
This happens because the bounding box of the top banner (including the tab) has been changed.

<img width="1107" alt="Screenshot 2023-07-06 at 4 16 23 pm" src="https://github.com/ACCESS-Hive/access-hive.github.io/assets/30042436/80e95d95-21b4-4f09-aaa9-3e3dcb44a862">

## Why
UI improvements to make users read the titles properly when clicked via toc.

## Close Criteria
- [x] Titles are displayed correctly when clicked from the table of contents.

**Comment by KAUR1984** [comment]
Can merge it as not breaking anything and not a high priority for now. Might just need to work on it in the future.

**Comment by KAUR1984** [comment]
Moving to parked for future tweaks.
