### ISSUE TITLE
BENCHCAB: Adding benchcab to ACCESS-Hive

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-NRI/access-hive.org.au#405]
## Description
Finding a placeholder for promoting the release of `benchcab` on the ACCESS-Hive. And should we be including `benchcab` in the **legacy release** or the **flagship release**? Might need to have a discussion with @ccarouge about placing and structure the tabs. 

## Why
For including `benchcab` as a supported topic on the ACCESS-Hive - https://github.com/CABLE-LSM/benchcab. 

## Close Criteria

- [x] Discuss with the team of where to place the `benchcab` information.
- [ ] Implement the suggested changes.

**Comment by ccarouge** [comment]
There are 2 possible places where to put information on `benchcab`:

- with CABLE
- with Model Evaluation and Diagnostics

I could put the information about benchcab under the model evaluation on Gadi. But for the moment, this section is for the tools we have in the `access-med` conda environment. benchcab is not distributed through this environment. I could add a paragraph to the index page for other tools distributed separately.

I want people to refer to the benchcab user guide to know how to use benchcab so I only need to put a short description and link to the user guide. In addition, benchcab only works for CABLE so far and for quite some time. So I could add a mention to it on the model components page about land. Then CABLE users get the whole information in one page, but does that confuse the layout of the whole website?

@rbeucher what do you think?

**Comment by rbeucher** [comment]
I think it's a bit early to put it in MED.
It's a benchmark tool to support develoemt of benchcab.
I would keep it with CABLE

**Comment by ccarouge** [comment]
OK, I'll put in a PR soon then.

**Comment by KAUR1984** [comment]
Sorry, was this issue in progress for this week? Happy to move it to Ready/Backlog if it's not a priority for this week :) @ccarouge

**Comment by ccarouge** [comment]
@KAUR1984 Sorry I completely forgot about it, since last July apparently :). I can get something in now if we want.

**Comment by ccarouge** [comment]
@KAUR1984 The pull request is ready. I'm not sure how you manage reviews anymore. Are the instructions in the PR template still correct?

**Comment by KAUR1984** [comment]
Thanks @ccarouge ! Whoops, the PR template needs to be updated with the latest instructions... For the PRs, feel free to assign @ACCESS-NRI/webops team as reviewers. This would ping the hive docs team to review and merge the PR. :)

**Comment by KAUR1984** [comment]
All done. Thanks for the PR @ccarouge!
