### ISSUE TITLE
WORKING GROUPS: Brainstorm UI ideas to find working groups information easily

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-NRI/access-hive.org.au#424]
## Description

The working groups information should be clear enough for the user to find and join on the hive page. Double check how to sync this information with the main access-nri website. 

## Why

To get users involved in different working groups. 

## Close Criteria

- [ ] Brainstorm ways of which sections should include the working groups information. 
- [ ] Implement on the hive page.

**Comment by KAUR1984** [comment]
Related to issue #425

**Comment by atteggiani** [comment]
The current [working groups page](https://access-hive.org.au/community_resources/community_working_groups/) links to the respective forum pages. 
I think this is good. 

I would close this issue.
@ACCESS-NRI/webops

**Comment by KAUR1984** [comment]
Happy to close this for now.
