### ISSUE TITLE
DEV WORKFLOW: Include the how to pull from `development` branch instructions 

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-NRI/access-hive.org.au#427]
## Description

In the `how to contribute` section on the access hive README (on development branch) - https://github.com/access-hive/access-hive.github.io/tree/development#how-to-contribute-draft and wiki - https://github.com/ACCESS-Hive/access-hive.github.io/wiki/2.-How-to-Contribute page.

## Why

To have the local branches in sync with the `development` branch which is actively being developed. 

## Close Criteria

- [x] Include the instructions for pulling, merging and resolving the merge conflicts (if any) in the `how to contribute` section. 
- [x] Might just also include the instructions of how to create a pr, and best practices.

**Comment by atteggiani** [comment]
The [Contribute on GitHub](https://access-hive.org.au/development-website/about/contribute/contribute_on_github/) page solves this.

I would close this issue.
@ACCESS-NRI/webops

**Comment by KAUR1984** [comment]
Agreed. Closing this one. :)
