### ISSUE TITLE
Low priority: Expand ACCESS-NRI Glossary

### ISSUE THREAD

**Issue by svenbuder** [ACCESS-NRI/access-hive.org.au#451]
Because we will link from the Hive to the main website glossary (https://www.access-nri.org.au/community/access-glossary), this issue can be used as a collection for new acronyms

**Comment by svenbuder** [comment]
ACCESS (Australian Community Climate and Earth System Simulator)
NRI (national research Infrastructure)
NCI (National Computational Infrastructure)
CMIP (Coupled Model Intercomparison Project)
MED (Model Evaluation and Diagnostic)
ILAMB ()
ESMValTool ()
COSIMA (Consortium for Ocean-Sea Ice Modelling in Australia)
ARE - 
gadi - 
ESM - 
cm - 
am - 
om -

**Comment by svenbuder** [comment]
Unified model: UM

**Comment by svenbuder** [comment]
PBS
NRI
CMIP
STASH –register?
OASIS-MCT
ILAMB
ESGF
 
Payu, Rose, Cycl ?
ARE, intake

**Comment by flicj191** [comment]
PCMDI - Program for Climate Model Diagnosis and Intercomparison, 
CMOR - Climate Model Output Rewriter ...CMOR tables [http://pcmdi.github.io/software/cmorTable/index.html](url)

**Comment by KAUR1984** [comment]
-- Sprint meeting notes: 

@NBateman-bit might just have a look for including the above acronyms in the ACCESS-NRI glossary.

> Note: Not a high priority issue as of now. :)

**Comment by atteggiani** [comment]
This issue is old and the [ACCESS-NRI glossary](I would close this issue.
@ACCESS-NRI/webops) links directly to the page on the NRI website, so it is not really relevant to ACCESS-Hive development. 

I would close this issue.
@ACCESS-NRI/webops

**Comment by KAUR1984** [comment]
Happy to close this one.
