### ISSUE TITLE
Models UI: Tune the access models landing image to be consistent with others

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-NRI/access-hive.org.au#470]
## Description

Currently, the image used to showcase the definition of configurations and experiments - https://access-hive.org.au/development_site/models/ could be tweaked a bit to be consistent with the other images used across the hive page. 

## Why

Ensuring consistent UI for images used across the hive page. 

## Close Criteria

- [ ] Brainstorm ways of improving the image UI and implement is accordingly.

**Comment by KAUR1984** [comment]
As we discussed in the meeting, @NBateman-bit would be the best person for work on this one :)

**Comment by atteggiani** [comment]
This issue is pretty old and the link is outdated.
Since we can address the issues related to the introduction image to models in #780 I will close this issue.
