### ISSUE TITLE
FROM SLACK: Restructure the model components page 

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-NRI/access-hive.org.au#489]
## Description

Max Proft
  [8:46 AM](https://access-nri.slack.com/archives/C05JD5D1NBA/p1689893218923569)
https://access-hive.org.au/development_site/models/model_components/
At the end of the page, after listing the origins of the components, include one line about how access is integrating these components together.

@atteggiani

**Comment by atteggiani** [comment]
We have the paragraphs "Configurations that use _component-name_" in all components pages now ([example](https://access-hive.org.au/development-website/models/model_components/atmosphere#configurations-that-use-UM)).
