### ISSUE TITLE
MED REVIEW: Review the MED content on Hive to make it similar to the other tabs (models, how to run, etc.)

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-NRI/access-hive.org.au#525]
## Description

~As discussed in the hive docs meeting, @kdruken  would perhaps be helping with reviewing the content of the MED pages on Hive.~
Re-organise MED content for consistency and clean up.

**Fix landing pages, navigation to match cards**
- replace cards with links where required (outside this tab)

**Separate into 2 categories**
- data (model variables in this category)
- model evaluation

## Why

For verifying the consistency of MED content with other tabs. 
Easier to read. 

## SubIssues created from this issue

- #644: Styling content clean up 
- #645: Content update 

## Close Criteria
- [ ] navigation between pages correct - similar to 'run a model'
- [ ] review

**Comment by KAUR1984** [comment]
Might need to ask someone to review this issue as Kelsey is busy with the workshop planning.

**Comment by KAUR1984** [comment]
In addition, @atteggiani would perhaps be looking into other sections too.

**Comment by flicj191** [comment]
_MED tree structure - hive-docs meeting 28/02/2024_
Data, Model Evaluation ~and Diagnostics~ _is distinction required?_
- data
    - format and variables
    - observational data
    - model data
- model evaluation (tiles for different tools)
    - ESMValTool
    - etc.

other notes:
community resources - some links integrated into other sections (MED) with support warnings, use links
