### ISSUE TITLE
CONTACT: Rework on the contact page to put more emphasis on using the Hive Forum

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-NRI/access-hive.org.au#540]
## Description
Restructure the contact page to put more emphasis on using the Hive forum and consistency between the main access-nri main website contact links. 

## Why
For making it clear for users about the contact option they have for the access-hive and access-nri.  

## Close Criteria
- [ ] Discuss with restructuring of the contact page and implement it on the hive. 
- [ ] Perhaps, think about changing the image too.

**Comment by atteggiani** [comment]
I think what can be done now is removing SLACK (as now it is only for internal usage) and then move the issue to low-priority.
@KAUR1984

**Comment by KAUR1984** [comment]
I agree with removing Slack from the contact page. I would also reword the heading - **_Places where you can find the ACCESS-NRI team_** to something more concise, such as, **_Get in contact with ACCESS-NRI team_** likewise .

**Comment by atteggiani** [comment]
Perfect, I'll work on it now.
