### ISSUE TITLE
Add icon to "call to actions"

### ISSUE THREAD

**Issue by atteggiani** [ACCESS-NRI/access-hive.org.au#544]
## Description
Add icon to notify "Call to actions / infos" in the website (e.g. "To join a project .....", "To create an account ....")

## Why
Clearer for users to know when they are required to do something

## Close Criteria
Add icon to all call to actions in the website

**Comment by atteggiani** [comment]
This is relatively old issue. 
I don't think we really need that. 

I would close this issue.
@ACCESS-NRI/webops

**Comment by KAUR1984** [comment]
Sounds good.
