### ISSUE TITLE
Trouble-shooting SSH connectivity is not supported 

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/access-hive.org.au#553]
## Description

The very nice new docs have a very nice and shiny section about how to enable ssh login with a keychain

https://access-hive.org.au/getting_started/#auto-login

## Why

I have no issues with the information provided, but I do have severe misgivings about including this sort of information in ACCESS supported documentation because ACCESS-NRI is not resourced to help users trouble short their ssh connectivity. It can be an incredibly time consuming process (ask me how I know) that we are not resourced for, nor is it part of our remit.

## Close Criteria

This section should either be removed entirely, moved to a different location (would make a good post on the forum) or a very prominent disclaimer should be added that this information is being provided as-is and ACCESS-NRI cannot help you trouble-shoot problems with your ssh keys or connectivity to systems: those queries should be directed to NCI.

**Comment by KAUR1984** [comment]
Thanks for raising this issue @aidanheerdegen! Noted as a discussion item for future Hive releases.
