### ISSUE TITLE
Add Climate Change AI to community resources

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-NRI/access-hive.org.au#576]
https://www.climatechange.ai/

**Comment by KAUR1984** [comment]
Thanks for raising this issue @rbeucher! Under which section of community resources should we add this link? Should it be added as just a reference link, or any other relating content should also be written?

**Comment by rbeucher** [comment]
There are some interesting tutorials for people wanting to use machine learning in their work.
Not sure where to put that on the Hive...
https://www.climatechange.ai/tutorials?

**Comment by KAUR1984** [comment]
Fixed in PR - https://github.com/ACCESS-NRI/access-hive.org.au/pull/691
