### ISSUE TITLE
RELEASE TAGS: Decide upon the new categories of the release tags on ZenHub

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-NRI/access-hive.org.au#581]
## Description
Currently, there are two release tags on ZenHub - `Legacy release` and `Flagship Release`. Might need a discussion with the development team to decide upon the future releases of the Hive. 

## Why
For efficiently utilising the release tags offered by ZenHub platform. 

## Close Criteria
- [ ] Discuss and plan the new release tags for the Hive on _Zenhub_.

**Comment by KAUR1984** [comment]
This is an important issue for planning ahead the future releases of Hive - need to take into account the **short-term** and **long-term** goals. 

We can create releases on GitHub - https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository and also need to decide the release names for categorizing zenhub issues. 

Moving this to ready to discuss in the coming Hive docs meeting.

**Comment by atteggiani** [comment]
I am not sure we need this. 
I understand planning on future releases is important, but the Hive development will be mostly driven by the models/tools developments. This means that whenever there is an update or new release in a model or tool, we will we will work on the respective documentation updates for the Hive, indipendently from the specific release name or if the modification is even included in a specific release.
I would close this issue.

@KAUR1984

**Comment by KAUR1984** [comment]
The releases are mostly along the lines of alpha/beta versioning. I am fine with not having them at all for now :)

**Comment by atteggiani** [comment]
Yeah I know, but with the Hive is not really applicable for now. 
I will close this issue.
