### ISSUE TITLE
Include a markdown file in another file: snippets extension

### ISSUE THREAD

**Issue by ccarouge** [ACCESS-NRI/access-hive.org.au#627]
## Description

Markdown has the [`snippets` extension](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/) that allows the inclusion of a Markdown file, or a section of a file, into another Markdown file. I was wondering if that would be useful for the ACCESS-Hive documentation. 

The snippets documentation mentions it is using it to save all the hyperlinks to a common file. This way there is only one place to go to update a link. I know when redesigning the site, we also wondered how to deal with common parts of the instructions to run models. Would something like `snippets` be of interest for that purpose or have we moved on?

@atteggiani @KAUR1984 (mentioning you since this is to gauge interest and you know the Hive best now)

**Comment by KAUR1984** [comment]
Thanks for that @ccarouge! That'd be really helpful as we work on cleaning file structures and minimising duplication on the Hive. Noted as a possibility to use on the Hive.

**Comment by ccarouge** [comment]
One nice feature is that it isn't limited to Markdown files within the documentation folder. Sean has used it to re-use the content of the README.md file within our home page. I see you are working on getting the contribution instructions in the README.md so you could then reuse that for the contribution page on the Hive itself.

**Comment by atteggiani** [comment]
Thank you for the infor @ccarouge! 

I agree, I think in general that could be useful in many different cases, regardless how we decide to structure the website in the future.

**Comment by KAUR1984** [comment]
Moving this to backlog for now :)
