### ISSUE TITLE
Check documentation on cosima cookbook after update to use intake catalog

### ISSUE THREAD

**Issue by atteggiani** [ACCESS-NRI/access-hive.org.au#633]
Check that cosima cookbook's documentation is up to date after the recent update with intake catalog.

**Comment by KAUR1984** [comment]
Hi guys, 

If not a priority for this week, happy to move this issue back to Ready/Backlog :)

**Comment by atteggiani** [comment]
Has this been carried out?

**Comment by flicj191** [comment]
Yea, page was reviewed, all links should be working correctly and doesn't go into detail with intake so it's good
