### ISSUE TITLE
`Sub Issue: 525` Update content in MED sections

### ISSUE THREAD

**Issue by flicj191** [ACCESS-NRI/access-hive.org.au#645]
## Description
Content needs to be reviewed and updated with new workflow releases.
Section will be reorganised as per #525 and cleaned up #644 then should be easier to navigate and update content to fit

## Why
Content needs to be up-to-date for users
linked to issues #525 #644 

## Close Criteria
[ ] review with @rbeucher

**Comment by atteggiani** [comment]
Has this been fixed with the recent MED PR review merge? #663

**Comment by flicj191** [comment]
yep, if theres more we can open specific issues
