### ISSUE TITLE
First step section

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-NRI/access-hive.org.au#654]
## Description

Remove suggestion to install WSL for users to use SSH terminal from Windows.

## Why

Windows 10 and 11 have built-in SSH now from the Windows terminal.
Installing WSL will be overkill for most of our Windows users.

## Close Criteria

Simplify the section. Linux. MacOSX and Windows have SSH terminal

**Comment by atteggiani** [comment]
@rbeucher 
Closing after fixing with #659
