### ISSUE TITLE
Incorrect link from License logo

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/access-hive.org.au#656]
## Description

Link to the licence in this page

https://access-hive.org.au/about/

Is incorrect and gives a 404

## Why

Image links to https://access-hive.org.au/about/license should be https://access-hive.org.au/about/License

## Close Criteria

Link is fixed.

**Comment by KAUR1984** [comment]
Noted as a bug fix. Thanks for flagging @aidanheerdegen!

**Comment by atteggiani** [comment]
@aidanheerdegen 
Closing after fixing with #659
