### ISSUE TITLE
CABLE: Update the Hive docs with the new Benchcab release

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-NRI/access-hive.org.au#658]
## Description
For the new release of the Benchcab, we might just create a new section under the `models` tab mentioning the new changes for the benchcab. 

## Why
For including the latest Benchcab instructions on the Hive docs.

## Close Criteria
- [ ] Discuss and include the updated benchcab documentation on the Hive.

**Comment by atteggiani** [comment]
Is this a duplicate of #405?
