### ISSUE TITLE
GitHub repo configuration

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/access-hive.org.au#682]
If the default branch for PRs is `development`, we can make that default branch for the repo, and then all PRs will use that as the base by default.

Both the protected branches (`development` and `main`) don't require approvals, signed commits, passing status checks or resolved conversations before merging. I would recommend these settings be activated.

**Comment by KAUR1984** [comment]
Thanks for the suggestions @aidanheerdegen! Noted as discussion points for our sprint meeting :)

**Comment by atteggiani** [comment]
Thanks @aidanheerdegen for everything you pointed out. 
After discussion during the sprint meeting, we decided to implement them all. 
So, the points to complete before closing this issue are:
- [ ] Set `development` as the default repo branch;
- Set branch protections rules for both `main` and `development` that include: 
  - [ ] required 1 approval before merging
  - [ ] all status check passed before merging
  - [ ] all conversations resolved before merging
  - [ ] required signed commits

**Comment by atteggiani** [comment]
All checks completed.
