### ISSUE TITLE
Wrong cice version listed for ACCESS-ESM1.5

### ISSUE THREAD

**Issue by blimlim** [ACCESS-NRI/access-hive.org.au#700]
## Description
The Hive documentation currently lists Cice5 as the sea ice component of ESM1.5:
https://github.com/ACCESS-NRI/access-hive.org.au/blob/bd572c72ab4c92c5cc4173f7fcfb6e3858a3c159/docs/models/configurations/access-esm.md?plain=1#L26-L27

and here
https://github.com/ACCESS-NRI/access-hive.org.au/blob/bd572c72ab4c92c5cc4173f7fcfb6e3858a3c159/docs/models/model_components/sea-ice.md?plain=1#L19

[though it actually uses Cice4.1](https://www.publish.csiro.au/es/pdf/ES19035). 
## Why
To make sure the information in the documentation is correct.
## Close Criteria
The documentation lists Cice4.1 as the sea ice model in ACCESS-ESM1.5

**Comment by atteggiani** [comment]
Connected to #702
