### ISSUE TITLE
HIVE: Make clear description of what Hive is about...

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-NRI/access-hive.org.au#712]
## Description
As per the webops meeting discussions, we might need to make it clear of what is "Hive" about. As per the consensus, it encompasses 2 parts - docs, and the forum. However, that's not documented anywhere on the main website or on the Hive docs.

## Why
To communicate clear objectives of what "Hive" is about.

## Close Criteria
- [ ] Change the title of the Hive docs website to reflect the "docs" more prominently. 
- [ ] Discuss among the team if there are any other changes required.

**Comment by atteggiani** [comment]
I would say this has been solved with the discussion about naming and the new [ACCESS-Hive page](https://www.access-nri.org.au/access-hive/) on the ACCESS-NRI website.

What we need to make sure is that in the Hive Docs, any reference to the Docs and the Forum are phrased correctly (`ACCESS-Hive Docs` or `Hive Docs`, and `ACCESS-Hive Forum` or `Hive Forum`).
I opened #733 for this.
Meanwhile I will close this issue.
