### ISSUE TITLE
USER SUPPORT: Update the first FAQ question with clarification for Hive

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-NRI/access-hive.org.au#723]
## Description
Update the first FAQ question on the Hive user support page, to remove any ambiguities in the "Hive" nomenclature. 

![Image](https://github.com/user-attachments/assets/2d0b1afd-3c38-45b3-88e9-6340e9444708)

## Why
Removing any confusions about the naming of hive. 

## Tasks
- [ ] Change the question title and description as per the latest naming conventions of the Hive.

**Comment by atteggiani** [comment]
This is a sub-issue of #733
