### ISSUE TITLE
UI: Align the Hive Docs with the latest UI suggestions before the workshop

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-NRI/access-hive.org.au#724]
https://anu365.sharepoint.com/:p:/r/sites/ACCESS-NRI/Shared%20Documents/A5.%20Infrastructure/WebOps/WebOps_Meetings/ACCESS-NRI%20Hive%20updates.pptx?d=w60c9b1b425424ce59b764cea51507acf&csf=1&web=1&e=z9WZyS

**Comment by atteggiani** [comment]
Subissue of #733
