### ISSUE TITLE
Add a document on how to use Spack develop

### ISSUE THREAD

**Issue by harshula** [ACCESS-NRI/access-hive.org.au#743]
## Description

We currently have a document on how to use Spack develop for `ACCESS-OM2` in the ACCESS-OM2 git repository:
https://github.com/ACCESS-NRI/ACCESS-OM2/blob/main/DEVELOPERS.md

We would like to make it available on Hive-Docs and generalise it to make it applicable to other models. e.g. `ACCESS-ESM1.5`.

## Why

We want users to be able to use Spack to modify a model's source code, built it and run it.

## Close Criteria

Spack develop document is available on Hive Docs.

**Comment by atteggiani** [comment]
Thanks for opening this issue @harshula!

I think the best approach for the addition of this content is the following:

1. Create a stand-alone page (something like "Build a model"), with the content you referred to above (initially I would take exactly the ACCESS-OM2 example as a reference). 
For example, another section called "Build a model" could be added to the "Run ACCESS-CM", "Run ACCESS-OM" and "Run ACCESS-ESM" sections. Something like this:

![test](https://github.com/user-attachments/assets/8f5fd4ec-487c-4679-b4bf-c5580d1dc319)

2. Differentiate the page for different models using tabs (see this example for [different ACCESS-OM2 versions](https://access-hive.org.au/models/configurations/access-om/#model-components))
3. Link the respective model page at the end of the "run <MODEL>" pages, in a paragraph that could be called "Custom <MODEL> build". 


What do you think?

**Comment by atteggiani** [comment]
Decreased priority to Medium (will be done after the workshop) after release stand-up. @harshula
