### ISSUE TITLE
Delete Home from tabs banner

### ISSUE THREAD

**Issue by atteggiani** [ACCESS-NRI/access-hive.org.au#782]
## Description 

Similarly to the main [ACCESS-NRI website](https://www.access-nri.org.au/), the Home button on the tabs banner is not needed, as long as the home page can be accessed by clicking on the main logo and title at the top left.

## Suggested actions

- [ ] I would remove Home from the tabs banner
- [ ] I would add a link to the home page also to the website title at the top-left (not only for the logo)
- [ ] Make sure the home page is accessible by clicking on the logo/title also on mobile devices

**Comment by atteggiani** [comment]
What do you think @ACCESS-NRI/webops ?

**Comment by heidinett** [comment]
I agree. The Home tab on the tabs banner of the landing page is redundant. Your alternative suggestion to link the home page top left is good.
