### ISSUE TITLE
fix links to pass check_links

### ISSUE THREAD

**Issue by atteggiani** [ACCESS-NRI/access-hive.org.au#826]
Fix the links urls in the MED section (and a few other sections) to pass `check_links` action. 

Requirements:
- All links should be formatted in markdown (if possible)
- All URLs should be formatted as an _absolute_ URL, starting with a forward slash (`/`) that represents the **base website** (`https://access-hive.org.au/` or `http://localhost:<port-number>/` if you are deploying locally through `mkdocs serve`)
- All URLs should be relative to the website [navigation tree](https://github.com/ACCESS-NRI/access-hive.org.au/blob/51278bfab8b1ec07dcfb752428ff9cbba7b89c8d/mkdocs.yml#L93-L187) set in the `mkdocs.yaml` file (this means also that no links should have the `index.md` file in it). 

Two practical examples:

### Wrong link --> link doesn't work

The reference link is the first link in https://access-hive.org.au/tutorials/ilamb:

https://github.com/ACCESS-NRI/access-hive.org.au/blob/51278bfab8b1ec07dcfb752428ff9cbba7b89c8d/docs/tutorials/ilamb.md?plain=1#L3

This link points to `/model_evaluation/model_evaluation_on_gadi/model_evaluation_on_gadi_ilamb`. This means there should be a page at https://access-hive.org.au/model_evaluation/model_evaluation_on_gadi/model_evaluation_on_gadi_ilamb, but if you click on this link it gives you a 404 error (page doesn't exist).
The link should be instead `/model_evaluation/evaluation_on_gadi/ilamb_workflow/`, pointing to https://access-hive.org.au/model_evaluation/evaluation_on_gadi/ilamb_workflow/

### Internal relative link (and also `index.md` file in it) --> link works but is falsely failed by the link_checker

The reference link is in https://access-hive.org.au/community_resources/community_med/community_med_recipes:

https://github.com/ACCESS-NRI/access-hive.org.au/blob/51278bfab8b1ec07dcfb752428ff9cbba7b89c8d/docs/community_resources/community_med/community_med_recipes.md?plain=1#L4

The link is `../../model_evaluation/index.md` (note the `../../` at the beginning and the `index.md` at the end). 
In this case the change is easier:
  1. Go to the linked page (if it works, otherwise refer to the example above)
  2. Copy the part after the base website
  3. Paste that as the new link

In the case above, the new link should be `/model_evaluation`.

## Tasks to fix the issue
- [ ] [check_links](https://github.com/ACCESS-NRI/access-hive.org.au/actions/workflows/check_links.yml) action passes.

**Comment by atteggiani** [comment]
@flicj191 Added more specification on this. 
To trigger the check_links action you only need to open a PR (also as a draft for testing while the links are changed).

**Comment by pboubel** [comment]
The ACCESS-NRI Intake Catalog section in the tutorials has a broken link but there is not yet a corresponding section in 'Model Evaluation'. Do we just want to link this to the Intake Catalog docs? (https://access-nri-intake-catalog.readthedocs.io/en/latest/index.html)

**Comment by atteggiani** [comment]
> The ACCESS-NRI Intake Catalog section in the tutorials has a broken link but there is not yet a corresponding section in 'Model Evaluation'. Do we just want to link this to the Intake Catalog docs? (https://access-nri-intake-catalog.readthedocs.io/en/latest/index.html)

Hi @pboubel, 
can you please point to the page in the Hive Docs where there is the broken link?

**Comment by pboubel** [comment]
> > The ACCESS-NRI Intake Catalog section in the tutorials has a broken link but there is not yet a corresponding section in 'Model Evaluation'. Do we just want to link this to the Intake Catalog docs? (https://access-nri-intake-catalog.readthedocs.io/en/latest/index.html)
> 
> Hi @pboubel, can you please point to the page in the Hive Docs where there is the broken link?

yes, here: https://access-hive.org.au/tutorials/intake/

**Comment by pboubel** [comment]
Also, there is a link to the 'recipe gallery' here https://access-hive.org.au/community_resources/community_med/community_med_recipes/
Doesn't seem to exist anywhere that I have looked

**Comment by flicj191** [comment]
hi @pboubel, the link in the intake tutorials page is supposed to point to here: 
https://access-hive.org.au/model_evaluation/data/model_catalogs/
the page was renamed to cover model data more broadly for the MED restructure before going into access-nri intake

you can leave the one in the community resources section, it was done a while ago and may need to look into the history, there's a separate issue to review it and organise so we will come to that with that issue #827 and #831

thanks for looking at this!

**Comment by atteggiani** [comment]
> you can leave the one in the community resources section, it was done a while ago and may need to look into the history, there's a separate issue to review it and organise so we will come to that with that issue #827 and #831

Even though we are going to properly address the community resources section in the issues linked, after this issue is fixed the link checker should pass. 
Therefore, for the moment, I would say to simply remove the sentence:

"We are trying to ingest more and more model evaluation and diagnostics recipes in your currated [recipe gallery on this website](https://access-hive.org.au/community_resources/model_evaluation/model_evaluation_recipe_gallery.md)."

Thank you @pboubel!

**Comment by pboubel** [comment]
@atteggiani So I have a few remaining cases that are failing check_links that I'm not sure how to deal with (see this run: https://github.com/ACCESS-NRI/access-hive.org.au/actions/runs/11545655642):

- Internal links that point to images or .md files (and one external link) that no longer exist, but the text/code that references these links has been commented out E.g. all the commented-out html code in docs/model_evaluation/evaluation_on_gadi/esmvaltool_workflow.md
- All four CMIP links at: https://access-hive.org.au/model_evaluation/evaluation_on_gadi/ilamb_workflow/#loading-the-ilamb-workflow-modules lead to a timeout 
- Link to UM partnership does not exist at bottom of: https://access-hive.org.au/models/model_components/atmosphere/
- This error:

[ERR] [%intel@19.0.3.199](https://github.com/ACCESS-NRI/access-hive.org.au/actions/runs/%intel@19.0.3.199) | Failed: Unreachable mail address: %intel@19.0.3.199: Invalid: Email doesn't exist or is syntactically incorrect 

check_links is mistaking this bit of text in the terminal window for an email it needs to check

**Comment by atteggiani** [comment]
> * Internal links that point to images or .md files (and one external link) that no longer exist, but the text/code that references these links has been commented out E.g. all the commented-out html code in docs/model_evaluation/evaluation_on_gadi/esmvaltool_workflow.md

Please just delete all the commented out text generating issues with links. 

> * All four CMIP links at: https://access-hive.org.au/model_evaluation/evaluation_on_gadi/ilamb_workflow/#loading-the-ilamb-workflow-modules lead to a timeout

I am not sure where those links wanted to point to. 
Do you have any idea @flicj191?

> * Link to UM partnership does not exist at bottom of: https://access-hive.org.au/models/model_components/atmosphere/

That link has been removed because the UM partneship has been "superseeded" by the [Momentum partneship](https://www.metoffice.gov.uk/research/approach/collaboration/momentum-partnership) for the next generation models.

I would substitute the link with the following link to a document about the UM partneship: https://www.metoffice.gov.uk/binaries/content/assets/metofficegovuk/pdf/research/foundation-science/um_partnership_handout.pdf

> * This error:
> 
> [ERR] [%intel@19.0.3.199](https://github.com/ACCESS-NRI/access-hive.org.au/actions/runs/%intel@19.0.3.199) | Failed: Unreachable mail address: %intel@19.0.3.199: Invalid: Email doesn't exist or is syntactically incorrect
> 
> check_links is mistaking this bit of text in the terminal window for an email it needs to check

This needs to be excluded from the check. 
It can be done by adding the following line:
```py
'^%intel@',
```
to the `exclude` field of the `lychee-config.toml`:

https://github.com/ACCESS-NRI/access-hive.org.au/blob/612f26b39cab6e2135263f98cdca3e2d8865f075/.github/workflows/lychee-config.toml#L4-L9

**Comment by flicj191** [comment]
> > * All four CMIP links at: https://access-hive.org.au/model_evaluation/evaluation_on_gadi/ilamb_workflow/#loading-the-ilamb-workflow-modules lead to a timeout
> 
> I am not sure where those links wanted to point to. Do you have any idea [@flicj191](https://github.com/flicj191)?

Sorry I missed this earlier!!
You mean in this section: https://access-hive.org.au/model_evaluation/evaluation_on_gadi/ilamb_workflow/#loading-the-ilamb-workflow-modules it looks like these were copied and condensed from the documentation: https://ilamb-workflow.readthedocs.io/en/latest/source/ILAMB.html#ilamb-cmip-confrontations-maintained-by-access-nri so those links don't go anywhere, I'll flag this with @rhaegar325 

But looking at that page, it looks like its an old version missing edits done from a review, I've found a newer version from my branches and and added to another branch and removed those broken links.
@pboubel  can you add the ilamb page from the branch here? https://github.com/ACCESS-NRI/access-hive.org.au/blob/flick/ilamb_edit/docs/model_evaluation/evaluation_on_gadi/ilamb_workflow.md

**Comment by pboubel** [comment]
Thanks @flicj191, I changed the ilamb page to what you have in that branch, with one small fix to a broken link (getting_started/first_steps/ -> getting_started/set_up_nci_account/).

@atteggiani However when I run link checker now there are 4 new errors that did not appear before (https://github.com/ACCESS-NRI/access-hive.org.au/actions/runs/11945377713). 

- a 404 error for https://www.lanl.gov/  (x2)
- a 504 error for https://journals.ametsoc.org/view/journals/bams/102/4/BAMS-D-19-0093.1.xml 
- a 504 error for https://doi.org/10.1175/JCLI-D-11-00256.1

These links all work fine for me and they passed the check last week so they may just be temporary errors? Let me know if you'd like me to do anything about them or just submit the pull request.

**Comment by atteggiani** [comment]
Hmm it might have been a temporary problem. 
But they do work fine for me too. 
Can you please try to run the link checker again and see if it still gets them as errors?

**Comment by pboubel** [comment]
> > These links all work fine for me and they passed the check last week so they may just be temporary errors? Let me know if you'd like me to do anything about them or just submit the pull request.
> 
> Hmm it might have been a temporary problem as they do work fine for me too. Can you please try to run the link checker again and see if it still gets them as errors?

@atteggiani The 504 errors have disappeared but no dice for https://www.lanl.gov/... Odd because it was not generating the 404 errors before.

**Comment by atteggiani** [comment]
> > > These links all work fine for me and they passed the check last week so they may just be temporary errors? Let me know if you'd like me to do anything about them or just submit the pull request.
> > 
> > 
> > Hmm it might have been a temporary problem as they do work fine for me too. Can you please try to run the link checker again and see if it still gets them as errors?
> 
> [@atteggiani](https://github.com/atteggiani) The 504 errors have disappeared but no dice for https://www.lanl.gov/... Odd because it was not generating the 404 errors before.

This is so weird and I'm not sure why it is happening. 

I would say for now let's not worry about it.
If you think the PR is ready (disregarding this problem mentioned here), please go on and mark it as reviewable and I'll review it (probably on Monday). 
Thank you! 😄
