### ISSUE TITLE
Change "Build an ACCESS model" to "Modify an ACCESS model's source code"

### ISSUE THREAD

**Issue by harshula** [ACCESS-NRI/access-hive.org.au#828]
## Description

During user testing of https://access-hive.org.au/models/run-a-model/build_a_model/ , Kial suggested substituting `Build` with `Recompile`.

I think "Recompile", "Rebuild" or "Modify" would be more descriptive than "Build".

**Comment by atteggiani** [comment]
Hmm, I see the point, but "build" is the technical term. 
We might be able to substitute it with "Compile an ACCESS model". 

I don't like the "re-" prefix (as in "Recompile"/"Rebuild"). The instructions specify how to compile/build a model. If any specific workflow involves a "re-compilation"/"re-build" that's ok, but the main concept should be without "re-".

**Comment by harshula** [comment]
Hi @atteggiani , I suspect the "re-" prefix is important because we already "build"/"compile" an ACCESS model. The end-user is likely to have already started a control run using the ACCESS-NRI built/compiled ACCESS model. They are then looking for instructions to re-build/re-compile the ACCESS model.

The titles of documents should be focussed on what the user will search for, not what you think makes sense. i.e. "Issue (symptom, problem, or question)—the issue is described in the requestor's words and phrases—what are they trying to do, what is not working, or what are they looking for?  It is helpful to view this field as belonging to the requestor (even though it may be captured by the responder). It must represent the requestor's perspective and context." (https://library.serviceinnovation.org/KCS/KCS_v6/KCS_v6_Practices_Guide/030/040/010/020)

**Comment by atteggiani** [comment]
Let's try to find a more specific title without needing the "re-" prefix.

**Comment by atteggiani** [comment]
What about "Modifying the source code of an ACCESS model"? @harshula

**Comment by harshula** [comment]
Hi @atteggiani , I'm happy to go with that compared to what we have now.
