### ISSUE TITLE
Can not load `payu` module following ACCESS-HIVE instructions for running `ACCESS-OM`

### ISSUE THREAD

**Issue by manodeep** [ACCESS-NRI/access-hive.org.au#852]
I am following the instructions [here](https://access-hive.org.au/models/run-a-model/run-access-om/#general-prerequisites) and I am a member of the groups `qv56` and `vk83`.

![Image](https://github.com/user-attachments/assets/daa777ef-6cc1-44e5-9dde-77065e69bc43)

I get an error for directory not found when I run:
```shell
[~ @gadi09] module use /g/data/vk83/modules
ERROR: Directory '/g/data/vk83/modules' not found
```

There is no `vk83` directory under `/g/data*` directories. May be there is a missing group membership that needs to be noted?

**Comment by anton-seaice** [comment]
Is this on a log-in node ?

**Comment by manodeep** [comment]
Yes - but I just tried that command again, and it works for me now. Probably was group membership info that didn't propagate through

**Comment by anton-seaice** [comment]
Oh possibly you need to do a fresh login for the /g/data to connect ?

**Comment by manodeep** [comment]
I would have thought that I used a new session but may be I used a persistent session (`screen`) on `gadi`. In any case, solved now :)
